---

# NOTE: To set up the virtual environment, we need to source the
# virtualenvwrapper script for each call -- and for the `source`
# command to work, we need to run Bash. E.g., you'll see this a lot:
#
#     args:
#       # Run Bash so `source` works.
#       executable: /bin/bash

# ***

- name: Dob dev » Stat project path
  stat: path="{{ zoidy_dob_dev_dob_working_tree }}"
  register: dob_path

- name: Dob dev » Verify project exists
  fail: msg="Please checkout dob first and update zoidy_dob_dev_dob_working_tree"
  when: not dob_path.stat.exists

# ***

- set_fact:
    # Lest: "ERROR: virtualenvwrapper could not find virtualenv in your path".
    VENV_PATH: "{{ zoidy_dob_dev_user_local_bin_dir }}:{{ ansible_env.PATH }}"

# ***

- name: Dob dev » Install Virtualenv and wrapper
  command: "pip3 install --user --upgrade {{ item }}"
  loop:
    - virtualenv
    - virtualenvwrapper

# ***

- name: Dob dev » Install github-release tool
  # Specify "-u"/update to always update projects previously got.
  command: "{{ zoidy_dob_dev_go }} get -u {{ item }}"
  environment:
    PATH: "{{ VENV_PATH }}"
    GOPATH: "{{ ansible_env.HOME }}/.gopath"
  loop:
    - github.com/meterup/github-release

# ***

- name: Dob dev » Remove existing virtual environment
  ansible.builtin.shell: >
    source {{ zoidy_dob_dev_virtualenvwrapper }} && \
    rmvirtualenv {{ zoidy_dob_dev_venv_name }}
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"

# ***

- name: Dob dev » Create virtual environment
  ansible.builtin.shell: >
    source {{ zoidy_dob_dev_virtualenvwrapper }} && \
    mkvirtualenv \
      -a {{ zoidy_dob_dev_dob_working_tree }} \
      --python={{ zoidy_dob_dev_python_bin }} \
      {{ zoidy_dob_dev_venv_name }}
  args:
    chdir: "{{ zoidy_dob_dev_dob_working_tree }}"
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"

# ***

# Setup dob project development via `make develop`, which will setup
# dob and related projects, i.e., so you don't have to `cd` to a dozen
# places and run `pip3 install -U -e .`.

# YOU: Ensure you've copied dob/requirements/ultra-editable.pip.example
#      to dob/requirements/ultra-editable.pip and setup paths to all the
#      related Python projects you also want to hack on.

# NOTE: We use `cd` in the shell command, rather than using the Ansible shell
#       module's `chdir`, because workon changes the working directory.

- name: Dob dev » Call make develop to pip-install editable projects
  ansible.builtin.shell: >
    source {{ zoidy_dob_dev_virtualenvwrapper }} && \
    workon {{ zoidy_dob_dev_venv_name }} && \
    cd {{ zoidy_dob_dev_dob_working_tree }} && \
    make develop
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"

# ***

# 2021-03-14 15:14: Unrelated to dob development, but allows you to access
# GnuCash bindings (and run fintech scripts) within a dob virtualenv. Why
# not.

# FIXME/2021-03-14 15:16: Added, but untested!

# NOTE: This creates the symlink regardless of if the target exists...
# which should be fine (you won't notice; Python won't care; and it'll
# work if you then later create the target).

- name: Dob dev » Hack in GnuCash Python bindings, because you can
  ansible.builtin.shell: >
    # FIXME/2021-03-14 15:18: Why do all the actions use \-continuations?
    # FIXME/2021-03-14 15:19: Does setting and referencing Bash variables work here?
    #   Specifically: user_site_packages_path
    #
    # test "$(command -v deactivate)" = "deactivate" && deactivate
    user_site_packages_path="$(python3 -m site --user-site)" && \
    source {{ zoidy_dob_dev_virtualenvwrapper }} && \
    workon {{ zoidy_dob_dev_venv_name }} && \
    cdsitepackages && \
    ( [ -h gnucash ] && rm gnucash || true ) && \
    ln -s ${user_site_packages_path}/gnucash
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"

# ***

